name: bookora
description: "Bookora - A cross-platform book shopping app built with Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 상태관리
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # 라우팅
  go_router: ^17.2.3

  # 네트워크 & 이미지
  dio: ^5.9.2
  cached_network_image: ^3.4.1

  # 애니메이션
  flutter_animate: ^4.5.2

  # 로컬 저장소
  hive_flutter: ^1.1.0

  # 백엔드
  supabase_flutter: ^2.12.4

  # 유틸
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.4-dev.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/